# Challenge - Titanic Survivors
### In this challenge, we ask you to build a predictive model that answers the question: “what sorts of people were more likely to survive?” using passenger data (ie name, age, gender, socio-economic class, etc)

# Import the Libraries

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing The Dataset

In [2]:
df1 = pd.read_csv('train.csv')
df2 = pd.read_csv('test.csv')
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
cols = df1.columns 
cols

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df1.columns.get_loc("Embarked") 

11

In [5]:
z1 = df1['Survived']


In [6]:
df1 = df1.drop('Survived',1)
df1

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
886          887       2                              Montvila, Rev. Juozas   
887          888       1                       Graham, Miss. Margaret Edith   
888          889       3           Johnston, Miss. Catherine Helen "Carrie"   
889          890       1                              Behr, Mr. Karl Howell   
890          891       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [7]:
df1['Survived']= z1 #df = df[['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp','Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived']
df1

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
886          887       2                              Montvila, Rev. Juozas   
887          888       1                       Graham, Miss. Margaret Edith   
888          889       3           Johnston, Miss. Catherine Helen "Carrie"   
889          890       1                              Behr, Mr. Karl Howell   
890          891       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [8]:
df1.index=df1['PassengerId']
df1

PassengerId  Pclass  \
PassengerId                        
1                      1       3   
2                      2       1   
3                      3       3   
4                      4       1   
5                      5       3   
...                  ...     ...   
887                  887       2   
888                  888       1   
889                  889       3   
890                  890       1   
891                  891       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  Survived  
PassengerId                                                                    
1                1      0         A/5 21171   7.2500   NaN        S         0  
2                1      0          PC 17599  71.2833   C85        C         1  
3                0      0  STON/O2. 3101282   7.9250   NaN        S         1  
4                1      0            113803  53.1000  C123        S         1  
5                0      0            373450   8.0500   NaN        S         0  
...            ...    ...               ...      ...   ...      ...       ...  
887              0      0            211536  13.0000   NaN        S         0  
888              0      0            112053  30.0000   B42        S         1  
889              1      2        W./C. 6607  23.4500   NaN        S         0  
890              0      0            111369  30.0000  C148        C         1  
891              0      0            370376   7.7500   NaN        Q         0  

[891 rows x 12 columns]

In [9]:
cols2 = df2.columns 
cols2

Index(['    PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [10]:
df2.index=df2['    PassengerId']
df2

PassengerId  Pclass  \
    PassengerId                            
892                          892       3   
893                          893       3   
894                          894       2   
895                          895       3   
896                          896       3   
...                          ...     ...   
1305                        1305       3   
1306                        1306       1   
1307                        1307       3   
1308                        1308       3   
1309                        1309       3   

                                                         Name     Sex   Age  \
    PassengerId                                                               
892                                          Kelly, Mr. James    male  34.5   
893                          Wilkes, Mrs. James (Ellen Needs)  female  47.0   
894                                 Myles, Mr. Thomas Francis    male  62.0   
895                                          Wirz, Mr. Albert    male  27.0   
896              Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0   
...                                                       ...     ...   ...   
1305                                       Spector, Mr. Woolf    male   NaN   
1306                             Oliva y Ocana, Dona. Fermina  female  39.0   
1307                             Saether, Mr. Simon Sivertsen    male  38.5   
1308                                      Ware, Mr. Frederick    male   NaN   
1309                                 Peter, Master. Michael J    male   NaN   

                 SibSp  Parch              Ticket      Fare Cabin Embarked  
    PassengerId                                                             
892                  0      0              330911    7.8292   NaN        Q  
893                  1      0              363272    7.0000   NaN        S  
894                  0      0              240276    9.6875   NaN        Q  
895                  0      0              315154    8.6625   NaN        S  
896                  1      1             3101298   12.2875   NaN        S  
...                ...    ...                 ...       ...   ...      ...  
1305                 0      0           A.5. 3236    8.0500   NaN        S  
1306                 0      0            PC 17758  108.9000  C105        C  
1307                 0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
1308                 0      0              359309    8.0500   NaN        S  
1309                 1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [11]:
df1 = df1.drop(['PassengerId','Name','Ticket', 'Fare', 'Cabin'],axis=1)
df1

Pclass     Sex   Age  SibSp  Parch Embarked  Survived
PassengerId                                                       
1                 3    male  22.0      1      0        S         0
2                 1  female  38.0      1      0        C         1
3                 3  female  26.0      0      0        S         1
4                 1  female  35.0      1      0        S         1
5                 3    male  35.0      0      0        S         0
...             ...     ...   ...    ...    ...      ...       ...
887               2    male  27.0      0      0        S         0
888               1  female  19.0      0      0        S         1
889               3  female   NaN      1      2        S         0
890               1    male  26.0      0      0        C         1
891               3    male  32.0      0      0        Q         0

[891 rows x 7 columns]

In [12]:

df2 = df2.drop(['Name','Ticket','Fare','    PassengerId','Cabin'],axis=1)
df2

Pclass     Sex   Age  SibSp  Parch Embarked
    PassengerId                                             
892                   3    male  34.5      0      0        Q
893                   3  female  47.0      1      0        S
894                   2    male  62.0      0      0        Q
895                   3    male  27.0      0      0        S
896                   3  female  22.0      1      1        S
...                 ...     ...   ...    ...    ...      ...
1305                  3    male   NaN      0      0        S
1306                  1  female  39.0      0      0        C
1307                  3    male  38.5      0      0        S
1308                  3    male   NaN      0      0        S
1309                  3    male   NaN      1      1        C

[418 rows x 6 columns]

In [13]:
x_train = df1.iloc[:, :-1].values# matrix of features
y_train = df1.iloc[:, -1].values#dependent variable
x_test = df2.iloc[:].values# matrix of features

# Importing Missing Data

In [14]:
#For Numerical Data
from sklearn.impute import SimpleImputer
imputer1 = SimpleImputer(missing_values=np.nan,strategy='median')
imputer2 = SimpleImputer(missing_values=np.nan,strategy='median')
imputer1.fit(x_train[: ,2:3])#to connect our imputer object to the matrix of features X
x_train[: ,2:3]=imputer1.transform(x_train[: ,2:3])# to apply the transformation
imputer2.fit(x_test[: ,2:3])
x_test[: ,2:3]=imputer2.transform(x_test[: ,2:3])

In [15]:
#For Categorical Data
imputer3 = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer3.fit(x_train[: ,5:6])
x_train[: ,5:6]=imputer3.transform(x_train[: ,5:6])# to apply the transformation
x_train

array([[3, 'male', 22.0, 1, 0, 'S'],
       [1, 'female', 38.0, 1, 0, 'C'],
       [3, 'female', 26.0, 0, 0, 'S'],
       ...,
       [3, 'female', 28.0, 1, 2, 'S'],
       [1, 'male', 26.0, 0, 0, 'C'],
       [3, 'male', 32.0, 0, 0, 'Q']], dtype=object)

In [16]:
x_test

array([[3, 'male', 34.5, 0, 0, 'Q'],
       [3, 'female', 47.0, 1, 0, 'S'],
       [2, 'male', 62.0, 0, 0, 'Q'],
       ...,
       [3, 'male', 38.5, 0, 0, 'S'],
       [3, 'male', 27.0, 0, 0, 'S'],
       [3, 'male', 27.0, 1, 1, 'C']], dtype=object)

In [17]:
#For Categorical Data
imputer4 = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer4.fit(x_test[: ,5:6])
x_test[: ,5:6]=imputer4.transform(x_test[: ,5:6])# to apply the transformation
x_test

array([[3, 'male', 34.5, 0, 0, 'Q'],
       [3, 'female', 47.0, 1, 0, 'S'],
       [2, 'male', 62.0, 0, 0, 'Q'],
       ...,
       [3, 'male', 38.5, 0, 0, 'S'],
       [3, 'male', 27.0, 0, 0, 'S'],
       [3, 'male', 27.0, 1, 1, 'C']], dtype=object)

## Encoding Independent variable or Categorical Data

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[5])],remainder='passthrough')
x_train=np.array(ct.fit_transform(x_train))
x_test=np.array(ct.fit_transform(x_test))

In [19]:
x_train[2]

array([0.0, 0.0, 1.0, 3, 'female', 26.0, 0, 0], dtype=object)

In [20]:
x_test[2]

array([0.0, 1.0, 0.0, 2, 'male', 62.0, 0, 0], dtype=object)

## Encoding Dependent variable or Ordinal Data


In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x_train[:,4]=le.fit_transform(x_train[:,4])
x_test[:,4]=le.fit_transform(x_test[:,4])
x_test

array([[0.0, 1.0, 0.0, ..., 34.5, 0, 0],
       [0.0, 0.0, 1.0, ..., 47.0, 1, 0],
       [0.0, 1.0, 0.0, ..., 62.0, 0, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 38.5, 0, 0],
       [0.0, 0.0, 1.0, ..., 27.0, 0, 0],
       [1.0, 0.0, 0.0, ..., 27.0, 1, 1]], dtype=object)

In [22]:
x_test

array([[0.0, 1.0, 0.0, ..., 34.5, 0, 0],
       [0.0, 0.0, 1.0, ..., 47.0, 1, 0],
       [0.0, 1.0, 0.0, ..., 62.0, 0, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 38.5, 0, 0],
       [0.0, 0.0, 1.0, ..., 27.0, 0, 0],
       [1.0, 0.0, 0.0, ..., 27.0, 1, 1]], dtype=object)

In [23]:
np.set_printoptions(threshold=np.inf)
x_train

array([[0.0, 0.0, 1.0, 3, 1, 22.0, 1, 0],
       [1.0, 0.0, 0.0, 1, 0, 38.0, 1, 0],
       [0.0, 0.0, 1.0, 3, 0, 26.0, 0, 0],
       [0.0, 0.0, 1.0, 1, 0, 35.0, 1, 0],
       [0.0, 0.0, 1.0, 3, 1, 35.0, 0, 0],
       [0.0, 1.0, 0.0, 3, 1, 28.0, 0, 0],
       [0.0, 0.0, 1.0, 1, 1, 54.0, 0, 0],
       [0.0, 0.0, 1.0, 3, 1, 2.0, 3, 1],
       [0.0, 0.0, 1.0, 3, 0, 27.0, 0, 2],
       [1.0, 0.0, 0.0, 2, 0, 14.0, 1, 0],
       [0.0, 0.0, 1.0, 3, 0, 4.0, 1, 1],
       [0.0, 0.0, 1.0, 1, 0, 58.0, 0, 0],
       [0.0, 0.0, 1.0, 3, 1, 20.0, 0, 0],
       [0.0, 0.0, 1.0, 3, 1, 39.0, 1, 5],
       [0.0, 0.0, 1.0, 3, 0, 14.0, 0, 0],
       [0.0, 0.0, 1.0, 2, 0, 55.0, 0, 0],
       [0.0, 1.0, 0.0, 3, 1, 2.0, 4, 1],
       [0.0, 0.0, 1.0, 2, 1, 28.0, 0, 0],
       [0.0, 0.0, 1.0, 3, 0, 31.0, 1, 0],
       [1.0, 0.0, 0.0, 3, 0, 28.0, 0, 0],
       [0.0, 0.0, 1.0, 2, 1, 35.0, 0, 0],
       [0.0, 0.0, 1.0, 2, 1, 34.0, 0, 0],
       [0.0, 1.0, 0.0, 3, 0, 15.0, 0, 0],
       [0.0, 0.0, 1.0, 1, 1, 28.0, 0,

## Feature Scaling

In [24]:
# Feature Scaling:Standardisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)   
x_test=sc.transform(x_test) 
x_train

array([[-0.48204268, -0.30756234,  0.61583843,  0.82737724,  0.73769513,
        -0.56573646,  0.43279337, -0.47367361],
       [ 2.0745051 , -0.30756234, -1.62380254, -1.56610693, -1.35557354,
         0.66386103,  0.43279337, -0.47367361],
       [-0.48204268, -0.30756234,  0.61583843,  0.82737724, -1.35557354,
        -0.25833709, -0.4745452 , -0.47367361],
       [-0.48204268, -0.30756234,  0.61583843, -1.56610693, -1.35557354,
         0.4333115 ,  0.43279337, -0.47367361],
       [-0.48204268, -0.30756234,  0.61583843,  0.82737724,  0.73769513,
         0.4333115 , -0.4745452 , -0.47367361],
       [-0.48204268,  3.25137334, -1.62380254,  0.82737724,  0.73769513,
        -0.1046374 , -0.4745452 , -0.47367361],
       [-0.48204268, -0.30756234,  0.61583843, -1.56610693,  0.73769513,
         1.89345853, -0.4745452 , -0.47367361],
       [-0.48204268, -0.30756234,  0.61583843,  0.82737724,  0.73769513,
        -2.10273333,  2.24747049,  0.76762988],
       [-0.48204268, -0.30756234

# Building the ANN

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:
# Initializing the ANN
ann= Sequential()
# Adding the input layer and the first hidden layer
ann.add(Dense(units=100, activation='relu'))
#Adding the 2nd hidden layer
ann.add(Dense(units=100, activation='relu'))
#Adding the output layer
ann.add(Dense(units=1, activation='sigmoid'))


# TRAINING THE ANN

In [27]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [28]:
ann.fit(x_train,y_train,batch_size=32 , epochs=100,verbose =2)

Epoch 1/100
28/28 - 1s - loss: 0.5656 - accuracy: 0.7486
Epoch 2/100
28/28 - 0s - loss: 0.4468 - accuracy: 0.8058
Epoch 3/100
28/28 - 0s - loss: 0.4289 - accuracy: 0.8103
Epoch 4/100
28/28 - 0s - loss: 0.4171 - accuracy: 0.8215
Epoch 5/100
28/28 - 0s - loss: 0.4088 - accuracy: 0.8260
Epoch 6/100
28/28 - 0s - loss: 0.4054 - accuracy: 0.8305
Epoch 7/100
28/28 - 0s - loss: 0.4004 - accuracy: 0.8406
Epoch 8/100
28/28 - 0s - loss: 0.3966 - accuracy: 0.8373
Epoch 9/100
28/28 - 0s - loss: 0.3962 - accuracy: 0.8384
Epoch 10/100
28/28 - 0s - loss: 0.3937 - accuracy: 0.8384
Epoch 11/100
28/28 - 0s - loss: 0.3927 - accuracy: 0.8373
Epoch 12/100
28/28 - 0s - loss: 0.3921 - accuracy: 0.8440
Epoch 13/100
28/28 - 0s - loss: 0.3878 - accuracy: 0.8485
Epoch 14/100
28/28 - 0s - loss: 0.3896 - accuracy: 0.8406
Epoch 15/100
28/28 - 0s - loss: 0.3857 - accuracy: 0.8429
Epoch 16/100
28/28 - 0s - loss: 0.3847 - accuracy: 0.8462
Epoch 17/100
28/28 - 0s - loss: 0.3836 - accuracy: 0.8384
Epoch 18/100
28/28 - 0s

# Predicting the test set results

In [29]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>.5)
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [

In [30]:
arr =np.array(df2.index)
arr = arr.reshape((len(arr),1))
arr

array([[ 892],
       [ 893],
       [ 894],
       [ 895],
       [ 896],
       [ 897],
       [ 898],
       [ 899],
       [ 900],
       [ 901],
       [ 902],
       [ 903],
       [ 904],
       [ 905],
       [ 906],
       [ 907],
       [ 908],
       [ 909],
       [ 910],
       [ 911],
       [ 912],
       [ 913],
       [ 914],
       [ 915],
       [ 916],
       [ 917],
       [ 918],
       [ 919],
       [ 920],
       [ 921],
       [ 922],
       [ 923],
       [ 924],
       [ 925],
       [ 926],
       [ 927],
       [ 928],
       [ 929],
       [ 930],
       [ 931],
       [ 932],
       [ 933],
       [ 934],
       [ 935],
       [ 936],
       [ 937],
       [ 938],
       [ 939],
       [ 940],
       [ 941],
       [ 942],
       [ 943],
       [ 944],
       [ 945],
       [ 946],
       [ 947],
       [ 948],
       [ 949],
       [ 950],
       [ 951],
       [ 952],
       [ 953],
       [ 954],
       [ 955],
       [ 956],
       [ 957],
       [ 9

In [31]:
print(y_pred.reshape(len(y_pred),1))

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 

In [32]:
final_arr = (np.concatenate((arr ,y_pred.reshape(len(y_pred),1)),1))
final_arr

array([[ 892,    0],
       [ 893,    0],
       [ 894,    0],
       [ 895,    0],
       [ 896,    0],
       [ 897,    0],
       [ 898,    1],
       [ 899,    0],
       [ 900,    1],
       [ 901,    0],
       [ 902,    0],
       [ 903,    0],
       [ 904,    1],
       [ 905,    0],
       [ 906,    1],
       [ 907,    1],
       [ 908,    0],
       [ 909,    0],
       [ 910,    0],
       [ 911,    0],
       [ 912,    1],
       [ 913,    1],
       [ 914,    1],
       [ 915,    1],
       [ 916,    1],
       [ 917,    0],
       [ 918,    1],
       [ 919,    0],
       [ 920,    0],
       [ 921,    0],
       [ 922,    0],
       [ 923,    0],
       [ 924,    0],
       [ 925,    0],
       [ 926,    1],
       [ 927,    0],
       [ 928,    0],
       [ 929,    1],
       [ 930,    0],
       [ 931,    0],
       [ 932,    0],
       [ 933,    0],
       [ 934,    0],
       [ 935,    1],
       [ 936,    1],
       [ 937,    0],
       [ 938,    0],
       [ 939,

In [33]:
final_arr.shape

(418, 2)

In [34]:
DF=  pd.DataFrame(final_arr )

In [37]:
DF.to_csv('data1.csv',header= ['PassengerId','Survived'],index = False)
